/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProductsCategorySlugRouteImport } from './routes/products/$categorySlug'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as PageSlugRouteImport } from './routes/page/$slug'
import { Route as CollectionSlugRouteImport } from './routes/collection/$slug'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AdminShopRouteImport } from './routes/admin/shop'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminDiscountsIndexRouteImport } from './routes/admin/discounts/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminCollectionsIndexRouteImport } from './routes/admin/collections/index'
import { Route as ApiCronRegenerateCollectionsRouteImport } from './routes/api/cron/regenerate-collections'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProductsVendorsRouteImport } from './routes/admin/products/vendors'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsDefinitionsRouteImport } from './routes/admin/products/definitions'
import { Route as AdminProductsCategoriesRouteImport } from './routes/admin/products/categories'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin/products/$productId'
import { Route as AdminPagesNewRouteImport } from './routes/admin/pages/new'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin/pages/$pageId'
import { Route as AdminOrdersNewRouteImport } from './routes/admin/orders/new'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders/$orderId'
import { Route as AdminDiscountsNewRouteImport } from './routes/admin/discounts/new'
import { Route as AdminDiscountsDiscountIdRouteImport } from './routes/admin/discounts/$discountId'
import { Route as AdminCollectionsNewRouteImport } from './routes/admin/collections/new'
import { Route as AdminCollectionsCollectionIdRouteImport } from './routes/admin/collections/$collectionId'
import { Route as AdminAnalyticsWishlistRouteImport } from './routes/admin/analytics/wishlist'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'
import { Route as AdminProductsVariantsVariantIdRouteImport } from './routes/admin/products/variants/$variantId'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ProductsCategorySlugRoute = ProductsCategorySlugRouteImport.update({
  id: '/$categorySlug',
  path: '/$categorySlug',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSlugRoute = PageSlugRouteImport.update({
  id: '/page/$slug',
  path: '/page/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopRoute = AdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsIndexRoute = AdminDiscountsIndexRouteImport.update({
  id: '/discounts/',
  path: '/discounts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCronRegenerateCollectionsRoute =
  ApiCronRegenerateCollectionsRouteImport.update({
    id: '/api/cron/regenerate-collections',
    path: '/api/cron/regenerate-collections',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsVendorsRoute = AdminProductsVendorsRouteImport.update({
  id: '/products/vendors',
  path: '/products/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsDefinitionsRoute =
  AdminProductsDefinitionsRouteImport.update({
    id: '/products/definitions',
    path: '/products/definitions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsCategoriesRoute = AdminProductsCategoriesRouteImport.update({
  id: '/products/categories',
  path: '/products/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesNewRoute = AdminPagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsNewRoute = AdminDiscountsNewRouteImport.update({
  id: '/discounts/new',
  path: '/discounts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsDiscountIdRoute =
  AdminDiscountsDiscountIdRouteImport.update({
    id: '/discounts/$discountId',
    path: '/discounts/$discountId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCollectionsNewRoute = AdminCollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsCollectionIdRoute =
  AdminCollectionsCollectionIdRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnalyticsWishlistRoute = AdminAnalyticsWishlistRouteImport.update({
  id: '/analytics/wishlist',
  path: '/analytics/wishlist',
  getParentRoute: () => AdminRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AdminProductsVariantsVariantIdRoute =
  AdminProductsVariantsVariantIdRouteImport.update({
    id: '/products/variants/$variantId',
    path: '/products/variants/$variantId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/thank-you': typeof ThankYouRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/page/$slug': typeof PageSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$categorySlug': typeof ProductsCategorySlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/analytics/wishlist': typeof AdminAnalyticsWishlistRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/categories': typeof AdminProductsCategoriesRoute
  '/admin/products/definitions': typeof AdminProductsDefinitionsRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/vendors': typeof AdminProductsVendorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/regenerate-collections': typeof ApiCronRegenerateCollectionsRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/products/variants/$variantId': typeof AdminProductsVariantsVariantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/thank-you': typeof ThankYouRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/page/$slug': typeof PageSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$categorySlug': typeof ProductsCategorySlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/analytics/wishlist': typeof AdminAnalyticsWishlistRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/categories': typeof AdminProductsCategoriesRoute
  '/admin/products/definitions': typeof AdminProductsDefinitionsRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/vendors': typeof AdminProductsVendorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/regenerate-collections': typeof ApiCronRegenerateCollectionsRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/products/variants/$variantId': typeof AdminProductsVariantsVariantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/thank-you': typeof ThankYouRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/page/$slug': typeof PageSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$categorySlug': typeof ProductsCategorySlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/analytics/wishlist': typeof AdminAnalyticsWishlistRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/categories': typeof AdminProductsCategoriesRoute
  '/admin/products/definitions': typeof AdminProductsDefinitionsRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/vendors': typeof AdminProductsVendorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/regenerate-collections': typeof ApiCronRegenerateCollectionsRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/products/variants/$variantId': typeof AdminProductsVariantsVariantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/products'
    | '/search'
    | '/shop'
    | '/thank-you'
    | '/account/orders'
    | '/admin/settings'
    | '/admin/shop'
    | '/api/upload'
    | '/auth/login'
    | '/auth/register'
    | '/collection/$slug'
    | '/page/$slug'
    | '/product/$slug'
    | '/products/$categorySlug'
    | '/account/'
    | '/admin/'
    | '/account/orders/$orderId'
    | '/admin/analytics/wishlist'
    | '/admin/collections/$collectionId'
    | '/admin/collections/new'
    | '/admin/discounts/$discountId'
    | '/admin/discounts/new'
    | '/admin/orders/$orderId'
    | '/admin/orders/new'
    | '/admin/pages/$pageId'
    | '/admin/pages/new'
    | '/admin/products/$productId'
    | '/admin/products/categories'
    | '/admin/products/definitions'
    | '/admin/products/new'
    | '/admin/products/vendors'
    | '/api/auth/$'
    | '/api/cron/regenerate-collections'
    | '/admin/collections'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/products/variants/$variantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/products'
    | '/search'
    | '/shop'
    | '/thank-you'
    | '/account/orders'
    | '/admin/settings'
    | '/admin/shop'
    | '/api/upload'
    | '/auth/login'
    | '/auth/register'
    | '/collection/$slug'
    | '/page/$slug'
    | '/product/$slug'
    | '/products/$categorySlug'
    | '/account'
    | '/admin'
    | '/account/orders/$orderId'
    | '/admin/analytics/wishlist'
    | '/admin/collections/$collectionId'
    | '/admin/collections/new'
    | '/admin/discounts/$discountId'
    | '/admin/discounts/new'
    | '/admin/orders/$orderId'
    | '/admin/orders/new'
    | '/admin/pages/$pageId'
    | '/admin/pages/new'
    | '/admin/products/$productId'
    | '/admin/products/categories'
    | '/admin/products/definitions'
    | '/admin/products/new'
    | '/admin/products/vendors'
    | '/api/auth/$'
    | '/api/cron/regenerate-collections'
    | '/admin/collections'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/products/variants/$variantId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/products'
    | '/search'
    | '/shop'
    | '/thank-you'
    | '/account/orders'
    | '/admin/settings'
    | '/admin/shop'
    | '/api/upload'
    | '/auth/login'
    | '/auth/register'
    | '/collection/$slug'
    | '/page/$slug'
    | '/product/$slug'
    | '/products/$categorySlug'
    | '/account/'
    | '/admin/'
    | '/account/orders/$orderId'
    | '/admin/analytics/wishlist'
    | '/admin/collections/$collectionId'
    | '/admin/collections/new'
    | '/admin/discounts/$discountId'
    | '/admin/discounts/new'
    | '/admin/orders/$orderId'
    | '/admin/orders/new'
    | '/admin/pages/$pageId'
    | '/admin/pages/new'
    | '/admin/products/$productId'
    | '/admin/products/categories'
    | '/admin/products/definitions'
    | '/admin/products/new'
    | '/admin/products/vendors'
    | '/api/auth/$'
    | '/api/cron/regenerate-collections'
    | '/admin/collections/'
    | '/admin/customers/'
    | '/admin/discounts/'
    | '/admin/orders/'
    | '/admin/pages/'
    | '/admin/products/'
    | '/admin/products/variants/$variantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  ThankYouRoute: typeof ThankYouRoute
  ApiUploadRoute: typeof ApiUploadRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  PageSlugRoute: typeof PageSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronRegenerateCollectionsRoute: typeof ApiCronRegenerateCollectionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/products/$categorySlug': {
      id: '/products/$categorySlug'
      path: '/$categorySlug'
      fullPath: '/products/$categorySlug'
      preLoaderRoute: typeof ProductsCategorySlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$slug': {
      id: '/page/$slug'
      path: '/page/$slug'
      fullPath: '/page/$slug'
      preLoaderRoute: typeof PageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shop': {
      id: '/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminShopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/': {
      id: '/admin/discounts/'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/': {
      id: '/admin/collections/'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/cron/regenerate-collections': {
      id: '/api/cron/regenerate-collections'
      path: '/api/cron/regenerate-collections'
      fullPath: '/api/cron/regenerate-collections'
      preLoaderRoute: typeof ApiCronRegenerateCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/vendors': {
      id: '/admin/products/vendors'
      path: '/products/vendors'
      fullPath: '/admin/products/vendors'
      preLoaderRoute: typeof AdminProductsVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/definitions': {
      id: '/admin/products/definitions'
      path: '/products/definitions'
      fullPath: '/admin/products/definitions'
      preLoaderRoute: typeof AdminProductsDefinitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/categories': {
      id: '/admin/products/categories'
      path: '/products/categories'
      fullPath: '/admin/products/categories'
      preLoaderRoute: typeof AdminProductsCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/new': {
      id: '/admin/pages/new'
      path: '/pages/new'
      fullPath: '/admin/pages/new'
      preLoaderRoute: typeof AdminPagesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/new': {
      id: '/admin/orders/new'
      path: '/orders/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/new': {
      id: '/admin/discounts/new'
      path: '/discounts/new'
      fullPath: '/admin/discounts/new'
      preLoaderRoute: typeof AdminDiscountsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/$discountId': {
      id: '/admin/discounts/$discountId'
      path: '/discounts/$discountId'
      fullPath: '/admin/discounts/$discountId'
      preLoaderRoute: typeof AdminDiscountsDiscountIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/new': {
      id: '/admin/collections/new'
      path: '/collections/new'
      fullPath: '/admin/collections/new'
      preLoaderRoute: typeof AdminCollectionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/$collectionId': {
      id: '/admin/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/admin/collections/$collectionId'
      preLoaderRoute: typeof AdminCollectionsCollectionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/wishlist': {
      id: '/admin/analytics/wishlist'
      path: '/analytics/wishlist'
      fullPath: '/admin/analytics/wishlist'
      preLoaderRoute: typeof AdminAnalyticsWishlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/admin/products/variants/$variantId': {
      id: '/admin/products/variants/$variantId'
      path: '/products/variants/$variantId'
      fullPath: '/admin/products/variants/$variantId'
      preLoaderRoute: typeof AdminProductsVariantsVariantIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShopRoute: typeof AdminShopRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticsWishlistRoute: typeof AdminAnalyticsWishlistRoute
  AdminCollectionsCollectionIdRoute: typeof AdminCollectionsCollectionIdRoute
  AdminCollectionsNewRoute: typeof AdminCollectionsNewRoute
  AdminDiscountsDiscountIdRoute: typeof AdminDiscountsDiscountIdRoute
  AdminDiscountsNewRoute: typeof AdminDiscountsNewRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
  AdminPagesNewRoute: typeof AdminPagesNewRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsCategoriesRoute: typeof AdminProductsCategoriesRoute
  AdminProductsDefinitionsRoute: typeof AdminProductsDefinitionsRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsVendorsRoute: typeof AdminProductsVendorsRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminDiscountsIndexRoute: typeof AdminDiscountsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsVariantsVariantIdRoute: typeof AdminProductsVariantsVariantIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShopRoute: AdminShopRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticsWishlistRoute: AdminAnalyticsWishlistRoute,
  AdminCollectionsCollectionIdRoute: AdminCollectionsCollectionIdRoute,
  AdminCollectionsNewRoute: AdminCollectionsNewRoute,
  AdminDiscountsDiscountIdRoute: AdminDiscountsDiscountIdRoute,
  AdminDiscountsNewRoute: AdminDiscountsNewRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrdersNewRoute: AdminOrdersNewRoute,
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
  AdminPagesNewRoute: AdminPagesNewRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsCategoriesRoute: AdminProductsCategoriesRoute,
  AdminProductsDefinitionsRoute: AdminProductsDefinitionsRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsVendorsRoute: AdminProductsVendorsRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminDiscountsIndexRoute: AdminDiscountsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsVariantsVariantIdRoute: AdminProductsVariantsVariantIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProductsRouteChildren {
  ProductsCategorySlugRoute: typeof ProductsCategorySlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCategorySlugRoute: ProductsCategorySlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  ThankYouRoute: ThankYouRoute,
  ApiUploadRoute: ApiUploadRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  PageSlugRoute: PageSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronRegenerateCollectionsRoute: ApiCronRegenerateCollectionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
